import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-slate-100`}>
        <nav className="w-full bg-slate-950 border-b border-slate-800 px-6 py-4 flex justify-between">
          <Link
            href="/"
            className="text-lg font-semibold text-white hover:text-cyan-300 transition-colors"
          >
            RWA Intel
          </Link>

          <Link
            href="/projects"
            className="text-sm text-slate-300 hover:text-white transition-colors"
          >
            Projects
          </Link>

          <Link
  href="/regulation"
  className="text-sm text-slate-300 hover:text-white transition-colors"
>
  Regulation
</Link>

        </nav>

        {children}
      </body>
    </html>
  );
}
